{% set name = "shortuuid" %}
{% set version = "0.4.2" %}
{% set sha256 = "47fa452b53fcf15427e539efd9fee8e625a9aebeb81db9339df7aeede52c2b61" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - disable-pep8-test.patch

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - shortuuid
  commands:
    - python -m unittest shortuuid.tests

about:
  home: https://github.com/stochastic-technologies/shortuuid/
  license: "BSD-3-Clause"
  license_file: COPYING
  summary: 'A generator library for concise, unambiguous and URL-safe UUIDs'
  description: |
    A library that generates short, pretty, unambiguous unique IDs by using an
    extensive, case-sensitive alphabet and omitting similar-looking letters and
    numbers.

extra:
  recipe-maintainers:
    - astamminger
