travis:
  secure:
    BINSTAR_TOKEN: TBBF4yX6zuFuzza56sqATZZlo9r9mArKRf1EsllUO26697ZLWrdIeIi1y+UXqs2BkCbU2g9P+HGRAmf0tTUmMYx5Bdpf1Gym6Hn69HjifiqCgLb5POm7BF3huFGPAQjxGSEiHgLRtkKrIwD9Llod3g+CVsnbLeShucFTkx56V+kthQhH5pdOVfoFmPMuj6ZBLZ2ntUA2CaGx7/ODEVfOJ6uiUu5sPTQVOKDqL1VHx8CD2D/w25dRtavCfY93klkkdmBXqrWB/EcN0nBZHUoUGAQAKuEupFX+LUqXXQ9J0guS+KjEURCulkhk2GYbh+9/E6jCi6cCxI7tO5fnT1gBsyMhhSnpp9h4u8eFOFbqucJfezWjEhz/w+iVm1Uebj7HXR6h0sdffsKjDUbNbkwjQ9Ercg2HpZoCHdAF8NzsKZjHPUp6pT0k9QjT3lF1Qi1HFrCRfruJxy1NeMUyS85kDRSYplZfPb2GecXVAP5JT8IG7CuSE0HrCChNEdeEBGbQSIxPL7yaCyhgEZyrAnSGeILdj0nKBT6jlIEV5B4k3IYV2z2s5UmQuImz5hErvpEzmbjE8SI4IbuOG499X0hHLcknNZQL/ADFilUo/9nyP39cPk/8DVeqxzIgFhEJNS09EE1tWdNv8pVSb81iBQdqmRwflMn6M8YALcfOCv5+kmo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
